apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proxy-ingress
  namespace: e-store
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /ratings-service(/|$)(.*)
            backend:
              serviceName: ratings-service
              servicePort: 8080
          - path: /customers-service(/|$)(.*)
            backend:
              serviceName: customers-service
              servicePort: 8080
